-- V1__metricsSchema.sql — the SHARED objects of the metrics schema
-- (CARDZATE_DB_GRAF): the dimensions every application group writes into,
-- the registry that routes ?groupId= to a group's fact tables, the archive
-- audit and the shared statistics job. Applied by the schema owner with
-- unqualified names; the metrics-consumer connects as that owner.
--
-- This file is the hosted environment's "shared across all groups" bundle,
-- reproduced verbatim so the same SQL runs in both places: UPPER_SNAKE
-- unquoted identifiers, BYTE semantics, idempotent CREATE blocks (-955 =
-- exists, -1408 = index exists). Per-group objects (<GROUP_ID>_METRICS and
-- friends) are NOT here — they are rendered from oracle/groups/<id>.json
-- into R__group_<id>.sql by oracle/groups/renderGroup.mjs.

-- ═══════════════════════════════════════════════════════════════════════
-- 1. LABEL — the label dimension, shared by all groups
-- ═══════════════════════════════════════════════════════════════════════
BEGIN
EXECUTE IMMEDIATE q'[CREATE TABLE LABEL (
        LABEL_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 CACHE 20) NOT NULL,
        GROUP_ID    VARCHAR2(30)   NOT NULL,        -- owning group's TABLE_PREFIX (e.g. 'CPS')
        LABEL_KEY   VARCHAR2(1000) NOT NULL,        -- original JMeter label text
        APPLICATION VARCHAR2(64),                   -- resolved per group by <PREFIX>_CLASSIFY_LABEL
        ENABLED     NUMBER(1) DEFAULT 1 NOT NULL,
        FIRST_SEEN  NUMBER(19),
        CONSTRAINT LABEL_PK PRIMARY KEY (LABEL_ID),
        CONSTRAINT LABEL_UK UNIQUE (GROUP_ID, LABEL_KEY)
    )]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
BEGIN
EXECUTE IMMEDIATE 'CREATE INDEX LABEL_APP_IDX ON LABEL (GROUP_ID, APPLICATION, LABEL_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
-- The group fact tables declare RELY foreign keys to the dimensions; Oracle
-- refuses those (ORA-25158) unless the referenced primary key is RELY too.
ALTER TABLE LABEL MODIFY CONSTRAINT LABEL_PK RELY;

-- ═══════════════════════════════════════════════════════════════════════
-- 2. RUN — the run dimension, shared by all groups
-- ═══════════════════════════════════════════════════════════════════════
BEGIN
EXECUTE IMMEDIATE q'[CREATE TABLE RUN (
        RUN_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 CACHE 20) NOT NULL,
        GROUP_ID     VARCHAR2(30)  NOT NULL,        -- owning group's TABLE_PREFIX
        RUN_KEY      VARCHAR2(255) NOT NULL,        -- original runId string
        BASE_RUN_KEY VARCHAR2(255),                 -- normalized runId (set by RUN_BIU)
        FIRST_SEEN   NUMBER(19),
        LAST_SEEN    NUMBER(19),
        CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT RUN_PK PRIMARY KEY (RUN_ID),
        CONSTRAINT RUN_UK UNIQUE (GROUP_ID, RUN_KEY)
    )]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
BEGIN
EXECUTE IMMEDIATE 'CREATE INDEX RUN_BASE_IDX ON RUN (GROUP_ID, BASE_RUN_KEY, RUN_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
ALTER TABLE RUN MODIFY CONSTRAINT RUN_PK RELY;

-- ═══════════════════════════════════════════════════════════════════════
-- 3. WORKER — one row per (run, worker), shared by all groups
-- ═══════════════════════════════════════════════════════════════════════
BEGIN
EXECUTE IMMEDIATE q'[CREATE TABLE WORKER (
        WORKER_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 CACHE 20) NOT NULL,
        RUN_ID           NUMBER        NOT NULL,
        GROUP_ID         VARCHAR2(30)  NOT NULL,
        WORKER_KEY       VARCHAR2(255) NOT NULL,    -- original workerId string
        REGION           VARCHAR2(64),
        JOINED_AT_SECOND NUMBER(19) DEFAULT 0 NOT NULL,  -- 0 = original fleet
        CONSTRAINT WORKER_PK PRIMARY KEY (WORKER_ID),
        CONSTRAINT WORKER_UK UNIQUE (RUN_ID, WORKER_KEY),
        CONSTRAINT WORKER_RUN_FK FOREIGN KEY (RUN_ID) REFERENCES RUN (RUN_ID)
    )]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
ALTER TABLE WORKER MODIFY CONSTRAINT WORKER_PK RELY;

-- ═══════════════════════════════════════════════════════════════════════
-- 4. GROUP_REGISTRY — routes ?groupId= to a group's fact tables
--    (named GROUP_REGISTRY, not GROUP — GROUP is an Oracle reserved word)
-- ═══════════════════════════════════════════════════════════════════════
BEGIN
EXECUTE IMMEDIATE q'[CREATE TABLE GROUP_REGISTRY (
        GROUP_ID           VARCHAR2(30)  NOT NULL,   -- value the producer sends as ?groupId=
        GROUP_NAME         VARCHAR2(255),
        TABLE_PREFIX       VARCHAR2(30)  NOT NULL,   -- object prefix + dimension GROUP_ID discriminator
        METRICS_TABLE      VARCHAR2(128) NOT NULL,   -- hot fact table the app INSERTs into
        METRICS_HIST_TABLE VARCHAR2(128),
        CLASSIFY_FN        VARCHAR2(128),
        ENABLED            NUMBER(1) DEFAULT 1 NOT NULL,
        CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT GROUP_REGISTRY_PK PRIMARY KEY (GROUP_ID)
    )]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════
-- 5. RUN_BIU — derive BASE_RUN_KEY (strip leading MA_, trailing _<n>_S<n>P<n>)
-- ═══════════════════════════════════════════════════════════════════════
CREATE OR REPLACE TRIGGER RUN_BIU
    BEFORE INSERT OR UPDATE OF RUN_KEY ON RUN
    FOR EACH ROW
BEGIN
    :NEW.BASE_RUN_KEY := SUBSTRB(
        REGEXP_REPLACE(REGEXP_REPLACE(:NEW.RUN_KEY, '^MA_', ''),
                       '(_[0-9]+)?_S[0-9]+P[0-9]+$', ''), 1, 255);
END;
/

-- ═══════════════════════════════════════════════════════════════════════
-- 6. METRICS_H_AUDIT — recovery audit for every <PREFIX>_METRICS → _H pass
-- ═══════════════════════════════════════════════════════════════════════
BEGIN
EXECUTE IMMEDIATE q'[CREATE TABLE METRICS_H_AUDIT (
        TABLE_PREFIX         VARCHAR2(30) NOT NULL,
        SOURCE_TABLE         VARCHAR2(128) NOT NULL,
        HISTORY_TABLE        VARCHAR2(128) NOT NULL,
        SOURCE_PARTITION     VARCHAR2(128) NOT NULL,
        PARTITION_HIGH_VALUE NUMBER(19) NOT NULL,
        TARGET_PARTITION     VARCHAR2(128) NOT NULL,
        STATUS               VARCHAR2(20) NOT NULL,
        SOURCE_ROWS          NUMBER,
        HISTORY_ROWS         NUMBER,
        STARTED_AT           TIMESTAMP,
        UPDATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        COMPLETED_AT         TIMESTAMP,
        ERROR_CODE           NUMBER,
        ERROR_MESSAGE        VARCHAR2(2000),
        CONSTRAINT METRICS_H_AUDIT_PK
            PRIMARY KEY (SOURCE_TABLE, PARTITION_HIGH_VALUE),
        CONSTRAINT METRICS_H_AUDIT_PART_UK
            UNIQUE (SOURCE_TABLE, SOURCE_PARTITION),
        CONSTRAINT METRICS_H_AUDIT_ST_CK CHECK
            (STATUS IN ('STAGING', 'STAGED', 'PUBLISHED', 'COMPLETE',
                        'BLOCKED_PUBLISH', 'BLOCKED_DROP', 'FAILED'))
    )]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════
-- 7. METRICS_MAINTAIN_SHARED — stale-only stats on the shared dimensions
-- ═══════════════════════════════════════════════════════════════════════
CREATE OR REPLACE PROCEDURE METRICS_MAINTAIN_SHARED AS
BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(
        USER, 'LABEL', options => 'GATHER AUTO', cascade => TRUE);
    DBMS_STATS.GATHER_TABLE_STATS(
        USER, 'RUN', options => 'GATHER AUTO', cascade => TRUE);
    DBMS_STATS.GATHER_TABLE_STATS(
        USER, 'WORKER', options => 'GATHER AUTO', cascade => TRUE);
END METRICS_MAINTAIN_SHARED;
/

-- Grants to the platform's users (METRICS_READER, METRICS_PURGER) are in
-- V2__controlPlaneSchema.sql, with the control plane — this file is the
-- hosted layout only. The consumer is the owner and needs none.
