package com.perf.orchestrator.kafka;

import com.perf.orchestrator.WorkerMetricBatch;
import com.perf.orchestrator.WorkerMetricEntry;
import io.confluent.kafka.schemaregistry.client.MockSchemaRegistryClient;
import io.confluent.kafka.serializers.KafkaAvroSerializer;
import io.confluent.kafka.serializers.KafkaAvroSerializerConfig;
import org.apache.kafka.clients.producer.MockProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.Serializer;
import org.apache.kafka.common.serialization.StringSerializer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.core.ProducerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.SoftAssertions.assertSoftly;

/**
 * Tests {@link KafkaMetricPublisher} (envelope-shape, K-1) by wrapping
 * {@link MockProducer} (from kafka-clients) in a tiny {@link ProducerFactory}
 * so a real {@link KafkaTemplate} drives it. Confluent's
 * {@link MockSchemaRegistryClient} provides Avro serialisation without a
 * running Schema Registry.
 *
 * <p>Why through {@link KafkaTemplate} rather than asserting on a Spring
 * test fixture: the publisher's contract is "the envelopes you publish reach
 * the topic, with the right key/value/topic, and counters reflect outcomes".
 * The cheapest way to verify that against the real {@link KafkaTemplate}
 * code path is the tiny {@link ProducerFactory} wrapper below.
 *
 * <p>The {@link WorkerMetricBatch} Avro class is generated by the
 * avro-maven-plugin during {@code mvn generate-sources}.
 */
@DisplayName("KafkaMetricPublisher")
class KafkaMetricPublisherTest {

    private static final String TOPIC     = "jmeter.metrics.perSecond";
    private static final String WORKER_ID = "jmeter-worker-0";
    private static final String REGION    = "us-east-1";
    private static final String RUN_ID    = "20250413-east";
    private static final String LABEL     = "POST /api/payment";

    /** Mock Schema Registry URL prefix — `mock://` keeps everything in-memory. */
    private static final String MOCK_SCHEMA_REGISTRY_URL = "mock://test-registry";

    private MockProducer<String, WorkerMetricBatch> mockProducer;
    private KafkaTemplate<String, WorkerMetricBatch> kafkaTemplate;
    private KafkaMetricPublisher                    publisher;

    @BeforeEach
    void setUp() {
        mockProducer  = newMockProducer(true);
        kafkaTemplate = templateFor(mockProducer);
        // null producerFactory is fine — these tests don't exercise enableMicrometer().
        publisher = new KafkaMetricPublisher(
                null, kafkaTemplate, MetricKeyStrategy.standard());
    }

    // -----------------------------------------------------------------------
    // Test infrastructure
    // -----------------------------------------------------------------------

    private static MockProducer<String, WorkerMetricBatch> newMockProducer(boolean autoComplete) {
        MockSchemaRegistryClient schemaRegistry = new MockSchemaRegistryClient();
        KafkaAvroSerializer avroSerializer = new KafkaAvroSerializer(schemaRegistry);
        avroSerializer.configure(
                Map.of(KafkaAvroSerializerConfig.SCHEMA_REGISTRY_URL_CONFIG,
                        MOCK_SCHEMA_REGISTRY_URL),
                false /* isKey */);

        Serializer<WorkerMetricBatch> valueSerializer = new Serializer<>() {
            @Override
            public byte[] serialize(String topic, WorkerMetricBatch data) {
                return avroSerializer.serialize(topic, data);
            }
            @Override
            public void close() {
                avroSerializer.close();
            }
        };

        return new MockProducer<>(autoComplete, new StringSerializer(), valueSerializer);
    }

    /**
     * Wraps the given {@link MockProducer} in a {@link ProducerFactory} so a
     * real {@link KafkaTemplate} can drive it. The factory hands KafkaTemplate
     * a Mockito-spy delegating {@link Producer} whose {@code close} methods
     * are stubbed no-ops — that mirrors what
     * {@code DefaultKafkaProducerFactory.CloseSafeProducer} does in production.
     */
    private static KafkaTemplate<String, WorkerMetricBatch> templateFor(
            MockProducer<String, WorkerMetricBatch> mockProducer) {
        Producer<String, WorkerMetricBatch> closeSafeProducer = org.mockito.Mockito.spy(mockProducer);
        org.mockito.Mockito.doNothing().when(closeSafeProducer).close();
        org.mockito.Mockito.doNothing().when(closeSafeProducer).close(org.mockito.ArgumentMatchers.any());

        ProducerFactory<String, WorkerMetricBatch> factory =
                new ProducerFactory<>() {
                    @Override
                    public Producer<String, WorkerMetricBatch> createProducer() {
                        return closeSafeProducer;
                    }
                };
        return new KafkaTemplate<>(factory);
    }

    // -----------------------------------------------------------------------
    // Fixture
    // -----------------------------------------------------------------------

    /** Builds a one-entry envelope keyed by REGION/WORKER_ID with the given label. */
    private static WorkerMetricBatch envelope(String label) {
        return envelope(List.of(label));
    }

    /** Builds an N-entry envelope keyed by REGION/WORKER_ID with one entry per label. */
    private static WorkerMetricBatch envelope(List<String> labels) {
        List<WorkerMetricEntry> entries = new ArrayList<>(labels.size());
        for (String label : labels) {
            entries.add(WorkerMetricEntry.newBuilder()
                    .setLabel(label)
                    .setThroughput(333L)
                    .setErrorCount(3L)
                    .setErrorRate(0.009)
                    .setAvgRespTimeMs(212.5)
                    .setP50Ms(185.0)
                    .setP90Ms(220.0)
                    .setP95Ms(250.0)
                    .setP99Ms(400.0)
                    .setMinMs(50.0)
                    .setMaxMs(3200.0)
                    .setRawMaxMs(3_700_000L)
                    .setBytesReceived(340_000L)
                    .setBytesSent(170_000L)
                    .setStatusCodes(Map.of("200", 330L, "503", 3L))
                    .setActiveThreads(80L)
                    .build());
        }
        return WorkerMetricBatch.newBuilder()
                .setWindowSecond(1_744_554_727L)
                .setWindowTimestamp("2025/04/13 14:32:07")
                .setRegion(REGION)
                .setWorkerId(WORKER_ID)
                .setRunId(RUN_ID)
                .setEntries(entries)
                .build();
    }

    // -----------------------------------------------------------------------
    // publishBatch behaviour
    // -----------------------------------------------------------------------

    @Nested
    @DisplayName("publishBatch (single envelope)")
    class PublishBatchBehaviour {

        @Test
        @DisplayName("exactly one Kafka record arrives for one envelope, regardless of how many entries it carries")
        void one_kafka_record_per_envelope() {
            // 200 labels in one envelope → still ONE Kafka record. This is the
            // load-bearing K-1 win on the wire.
            List<String> labels = new ArrayList<>();
            for (int i = 0; i < 200; i++) labels.add("GET /endpoint/" + i);

            publisher.publishBatch(envelope(labels), TOPIC);

            assertThat(mockProducer.history()).hasSize(1);
            assertThat(mockProducer.history().get(0).value().getEntries()).hasSize(200);
        }

        @Test
        @DisplayName("published record uses the K-1 partition key: {region}|{workerId}|{windowSecond}")
        void record_uses_envelope_scoped_key() {
            publisher.publishBatch(envelope(LABEL), TOPIC);

            String expectedKey = "us-east-1|jmeter-worker-0|1744554727";
            assertThat(mockProducer.history().get(0).key()).isEqualTo(expectedKey);
        }

        @Test
        @DisplayName("envelope with mixed labels still uses one key — same pod-second always lands on one partition")
        void mixed_label_envelope_still_one_key() {
            publisher.publishBatch(envelope(List.of("POST /a", "GET /b", "DELETE /c")), TOPIC);

            assertThat(mockProducer.history().get(0).key())
                    .as("envelope key drops the label axis — same (pod, second), same partition regardless of entries")
                    .isEqualTo("us-east-1|jmeter-worker-0|1744554727");
        }

        @Test
        @DisplayName("published record targets the per-call topic — proves Phase G fix routes per-run, not from boot config")
        void record_targets_per_call_topic() {
            publisher.publishBatch(envelope(LABEL), TOPIC);

            assertThat(mockProducer.history().get(0).topic()).isEqualTo(TOPIC);
        }

        @Test
        @DisplayName("consecutive publishBatch calls can target different topics — same warm producer")
        void consecutive_calls_target_different_topics() {
            publisher.publishBatch(envelope("POST /a"), "jmeter.metrics.appA");
            publisher.publishBatch(envelope("POST /b"), "jmeter.metrics.appB");

            assertThat(mockProducer.history()).hasSize(2);
            assertThat(mockProducer.history().get(0).topic()).isEqualTo("jmeter.metrics.appA");
            assertThat(mockProducer.history().get(1).topic()).isEqualTo("jmeter.metrics.appB");
        }

        @Test
        @DisplayName("rejects blank topic — fail fast rather than land on the broker's default")
        void rejects_blank_topic() {
            assertThatThrownBy(() -> publisher.publishBatch(envelope(LABEL), "  "))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("topic");
        }

        @Test
        @DisplayName("envelope value carries the 5 envelope-level identity fields + entries[]")
        void envelope_value_carries_all_fields() {
            publisher.publishBatch(envelope(LABEL), TOPIC);

            WorkerMetricBatch sent = mockProducer.history().get(0).value();
            assertSoftly(softly -> {
                softly.assertThat(sent.getWorkerId().toString()).isEqualTo(WORKER_ID);
                softly.assertThat(sent.getRegion().toString()).isEqualTo(REGION);
                softly.assertThat(sent.getRunId().toString()).isEqualTo(RUN_ID);
                softly.assertThat(sent.getWindowSecond()).isEqualTo(1_744_554_727L);
                softly.assertThat(sent.getEntries()).hasSize(1);

                WorkerMetricEntry e = sent.getEntries().get(0);
                softly.assertThat(e.getLabel().toString()).isEqualTo(LABEL);
                softly.assertThat(e.getThroughput()).isEqualTo(333L);
                softly.assertThat(e.getErrorCount()).isEqualTo(3L);
                softly.assertThat(e.getBytesReceived()).isEqualTo(340_000L);
                softly.assertThat(e.getActiveThreads()).isEqualTo(80L);
            });
        }

        @Test
        @DisplayName("published count increments after successful delivery")
        void published_count_increments_on_success() {
            publisher.publishBatch(envelope(LABEL), TOPIC);

            assertThat(publisher.getPublishedCount()).isEqualTo(1L);
        }

        @Test
        @DisplayName("failed count remains zero when delivery succeeds")
        void failed_count_stays_zero_on_success() {
            publisher.publishBatch(envelope(LABEL), TOPIC);

            assertThat(publisher.getFailedCount()).isZero();
        }

        @Test
        @DisplayName("rejects null envelope")
        void rejects_null_envelope() {
            assertThatThrownBy(() -> publisher.publishBatch(null, TOPIC))
                    .isInstanceOf(NullPointerException.class);
        }
    }

    // -----------------------------------------------------------------------
    // publishAll behaviour
    // -----------------------------------------------------------------------

    @Nested
    @DisplayName("publishAll")
    class PublishAll {

        @Test
        @DisplayName("sends one Kafka record per envelope in the list")
        void sends_one_record_per_envelope() {
            List<WorkerMetricBatch> envelopes = List.of(
                    envelope("POST /api/payment"),
                    envelope("GET /api/account"),
                    envelope("DELETE /api/session")
            );

            publisher.publishAll(envelopes, TOPIC);

            assertThat(mockProducer.history()).hasSize(3);
        }

        @Test
        @DisplayName("each record carries its envelope's first entry's label — proves order preserved")
        void each_record_carries_its_envelope() {
            List<WorkerMetricBatch> envelopes = List.of(
                    envelope("POST /api/payment"),
                    envelope("GET /api/account")
            );

            publisher.publishAll(envelopes, TOPIC);

            List<String> firstEntryLabels = mockProducer.history().stream()
                    .map(ProducerRecord::value)
                    .map(b -> b.getEntries().get(0).getLabel().toString())
                    .toList();

            assertThat(firstEntryLabels).containsExactlyInAnyOrder("POST /api/payment", "GET /api/account");
        }

        @Test
        @DisplayName("is a no-op for an empty list — does not send to Kafka at all")
        void empty_list_sends_nothing() {
            publisher.publishAll(List.of(), TOPIC);

            assertThat(mockProducer.history()).isEmpty();
        }

        @Test
        @DisplayName("rejects null list")
        void rejects_null_list() {
            assertThatThrownBy(() -> publisher.publishAll(null, TOPIC))
                    .isInstanceOf(NullPointerException.class);
        }
    }

    // -----------------------------------------------------------------------
    // Delivery failure behaviour
    // -----------------------------------------------------------------------

    @Nested
    @DisplayName("delivery failure handling")
    class DeliveryFailureHandling {

        @Test
        @DisplayName("failed count increments when the broker rejects an envelope")
        void failed_count_increments_on_rejection() {
            // autoComplete=false: we control when sends complete
            MockProducer<String, WorkerMetricBatch> failingProducer = newMockProducer(false);
            KafkaMetricPublisher failingPublisher = new KafkaMetricPublisher(
                    null, templateFor(failingProducer), MetricKeyStrategy.standard());

            failingPublisher.publishBatch(envelope(LABEL), TOPIC);

            failingProducer.errorNext(new RuntimeException("broker unavailable"));

            assertThat(failingPublisher.getFailedCount()).isEqualTo(1L);
        }
    }

    // -----------------------------------------------------------------------
    // Per-run flush behaviour
    // -----------------------------------------------------------------------

    @Nested
    @DisplayName("flush — per-run end-of-stream")
    class FlushBehaviour {

        @Test
        @DisplayName("flush() drives MockProducer's pending queue — published count reflects flushed envelopes")
        void flush_drains_pending_records() {
            MockProducer<String, WorkerMetricBatch> lazyProducer = newMockProducer(false);
            KafkaMetricPublisher lazyPublisher = new KafkaMetricPublisher(
                    null, templateFor(lazyProducer), MetricKeyStrategy.standard());

            lazyPublisher.publishBatch(envelope("POST /api/payment"), TOPIC);
            lazyPublisher.publishBatch(envelope("GET /api/account"), TOPIC);

            assertThat(lazyProducer.history()).hasSize(2);
            assertThat(lazyPublisher.getPublishedCount()).isZero();

            lazyPublisher.flush();

            assertThat(lazyPublisher.getPublishedCount())
                    .as("flush() must trigger the delivery callbacks for all queued envelopes")
                    .isEqualTo(2L);
        }

        @Test
        @DisplayName("flush() on a closed publisher is a no-op — does not throw IllegalStateException")
        void flush_after_close_is_safe() {
            publisher.close();

            org.assertj.core.api.Assertions.assertThatCode(publisher::flush)
                    .doesNotThrowAnyException();
        }
    }

    // -----------------------------------------------------------------------
    // Micrometer wiring
    // -----------------------------------------------------------------------

    @Nested
    @DisplayName("enableMicrometer — Actuator metric binding")
    class EnableMicrometerBehaviour {

        @Test
        @DisplayName("rejects null meter registry — fail fast at boot rather than silently producing zero metrics")
        void rejects_null_meter_registry() {
            com.perf.orchestrator.config.OrchestratorConfig cfg = realConfigForMicrometerTest();
            KafkaMetricPublisher real = KafkaMetricPublisher.create(cfg);
            try {
                assertThatThrownBy(() -> real.enableMicrometer(null))
                        .isInstanceOf(NullPointerException.class)
                        .hasMessageContaining("meterRegistry");
            } finally {
                real.close();
            }
        }

        @Test
        @DisplayName("attaching a real MicrometerProducerListener to the factory does not throw — wiring is type-correct")
        void wiring_is_type_correct() {
            com.perf.orchestrator.config.OrchestratorConfig cfg = realConfigForMicrometerTest();
            KafkaMetricPublisher real = KafkaMetricPublisher.create(cfg);
            try {
                io.micrometer.core.instrument.simple.SimpleMeterRegistry registry =
                        new io.micrometer.core.instrument.simple.SimpleMeterRegistry();
                org.assertj.core.api.Assertions.assertThatCode(() -> real.enableMicrometer(registry))
                        .as("MicrometerProducerListener type parameters must align with " +
                            "DefaultKafkaProducerFactory.addListener — pre-K-1 regression guard")
                        .doesNotThrowAnyException();
            } finally {
                real.close();
            }
        }

        @Test
        @DisplayName("rejects enableMicrometer on a test-constructed publisher (null producerFactory)")
        void rejects_when_no_producer_factory() {
            io.micrometer.core.instrument.simple.SimpleMeterRegistry registry =
                    new io.micrometer.core.instrument.simple.SimpleMeterRegistry();
            assertThatThrownBy(() -> publisher.enableMicrometer(registry))
                    .isInstanceOf(IllegalStateException.class)
                    .hasMessageContaining("create(config)");
        }

        /** Minimal valid config that {@link KafkaMetricPublisher#create(com.perf.orchestrator.config.OrchestratorConfig) create()} can build a producer factory from. */
        private static com.perf.orchestrator.config.OrchestratorConfig realConfigForMicrometerTest() {
            java.util.Map<String, String> env = new java.util.HashMap<>();
            env.put("POD_NAME", "jmeter-test-pod");
            env.put("TEST_REGION", "us-east-1");
            env.put("RUN_ID", "test-run-id");
            env.put("JTL_PATH", "/results/results.jtl");
            env.put("SENTINEL_PATH", "/results/.done");
            env.put("KAFKA_BROKERS", "localhost:9092");
            env.put("SCHEMA_REGISTRY_URL", "http://localhost:8081");
            env.put("KAFKA_TOPIC", "jmeter.metrics.perSecond");
            return com.perf.orchestrator.config.OrchestratorConfig.from(env);
        }
    }

    // -----------------------------------------------------------------------
    // Close behaviour — JVM shutdown only
    // -----------------------------------------------------------------------

    @Nested
    @DisplayName("close — JVM shutdown")
    class CloseAndFlush {

        @Test
        @DisplayName("close() flushes pending envelopes before disposing — published count reflects them")
        void close_flushes_before_disposing() {
            MockProducer<String, WorkerMetricBatch> lazyProducer = newMockProducer(false);
            KafkaMetricPublisher lazyPublisher = new KafkaMetricPublisher(
                    null, templateFor(lazyProducer), MetricKeyStrategy.standard());

            lazyPublisher.publishBatch(envelope(LABEL), TOPIC);
            assertThat(lazyProducer.history()).hasSize(1);

            lazyPublisher.close();

            assertThat(lazyPublisher.getPublishedCount())
                    .as("flush() inside close() must trigger delivery callbacks for all queued envelopes")
                    .isEqualTo(1L);
        }

        @Test
        @DisplayName("second close() call is a no-op — does not throw IllegalStateException")
        void double_close_is_safe() {
            publisher.close();

            org.assertj.core.api.Assertions.assertThatCode(publisher::close)
                    .doesNotThrowAnyException();
        }
    }
}
